### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [stape-io/activecampaign-tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUri should be used on user provided values that are then used to create your url. These methods returns an encoded Uniform Resource Identifier (URI) by escaping special characters. It returns a string that represents the provided string encoded as a URI. You should use this method on data.apiUrl when generating the url
let url = data.apiUrl + '/api/3/contact/sync';

**Comment by Bukashk0zzz** [comment]
Fixed https://github.com/gtm-server/activecampaign-tag/commit/40384621fd0350404d9540cf31f258e2a4bf939a

Thanks.
