### ISSUE TITLE
ActiveCampaign Even Tracking Tag Missing

### ISSUE THREAD

**Issue by michelmitri0** [stape-io/activecampaign-tag#3]
ActiveCampaign Custom Tag Does not exist in GTM Custom list. I have searched for it but cannot seem to find it. 
can you please advise how to install it? 
this is what I get when I try to look it up

![image](https://user-images.githubusercontent.com/116738025/198050908-001ee466-b636-43e6-b1ea-77bf29639604.png)

**Comment by Bukashk0zzz** [comment]
This template is for Server Side GTM, and you try to find it in WEB GTM.

You can follow this guide https://stape.io/blog/how-to-integrate-activecampaign-with-the-website-using-google-tag-manager-server-container
