### ISSUE TITLE
I just cant find the template in tag gallery

### ISSUE THREAD

**Issue by Hamdan85** [stape-io/activecampaign-tag#7]
Im trying to use the tag but I cant find it. 

Do you guys know why?

![image](https://user-images.githubusercontent.com/1886026/216427561-e7bb3994-d25c-4ce7-8e8e-0e4188ef098d.png)

**Comment by Bukashk0zzz** [comment]
Because you try to find in Web GTM.
This tag is for Server GTM.

**Comment by Hamdan85** [comment]
Thanks for the information. Is there a reason you guy's didn't implement
for frontend as well that I should be aware of?

**Comment by Bukashk0zzz** [comment]
Not all functionality can be done on the front end because Active Campaign API requires a private key.
Another thing is if you do this on the server, you don't need to load additional JS on the page.
